[package]
name = "dioxus-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33", features = ["serde"] }
dioxus = "0.4.3"
dioxus-web = "0.4.3"
serde = "1.0.195"
