[package]
name = "birthday-paradox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
chrono-english = "0.1.7"
plotters = "0.3.5"
rand = "0.8.5"
regex-lite = "0.1.5"
